# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170828_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='lunbotu'),
        ),
    ]
